### GET products
GET http://localhost:3000/api/products?description=phone&minPrice=100&maxPrice=500

### GET single products
GET http://localhost:3000/api/products/1

### Post product
Post http://localhost:3000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlclR5cGUiOiJ1c2VyIiwiaWF0IjoxNzc4MjcxNDU3LCJleHAiOjE3Nzg4NzYyNTd9.Mx9ZBdQvHydn08L67-3QmW4NQoRcrdBdDyp4Y9Skuus

{
    "title": "screen",
    "description": "new screen",
    "price": 300
}

### Update product
PUT http://localhost:3000/api/products/1
Content-Type: application/json

{
    "title": "new product updated",
    "price": 80
}

### Update product
DELETE http://localhost:3000/api/products/1
