### GET Users
GET http://localhost:5432/api/users


### Create User
POST  http://localhost:3000/api/users/auth/register
Content-Type: application/json

{
    "email": "ahmed@gmail.com",
    "password":"12345",
    "username": "ahmed"
}

### Login User
POST  http://localhost:3000/api/users/auth/login
Content-Type: application/json

{
    "email": "ahmed@gmail.com",
    "password":"12345"
}



